[[language]]
name = "rust"

[language.formatter]
command = 'cargo fmt --all -- --check'

[language-server.rust-analyzer]
environment.RUSTUP_TOOLCHAIN = "stable"

[language-server.rust-analyzer.config]
check.allTargets = false
cargo.target = "thumbv7em-none-eabihf"

