[target.thumbv7em-none-eabihf]
runner = [
  "probe-rs",
  "run",
  "--chip",
  "nRF52833_xxAA",
  "--log-format",
  "{t} {L} {s}",
]
# runner = [
#   "probe-rs",
#   "gdb",
#   "--chip",
#   "nRF52833_xxAA",
# ]

rustflags = [
  "-C", "link-arg=-Tlink.x",
  # "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"
